#!/usr/bin/env python3
"""Kafka producer for Calendar collaboration events.

Reads edges.csv, filters channel == 'calendar', and publishes TWO events per
edge (bidirectional: the invite sender and the invite receiver each get an event).
Both events use direction='invited' since a calendar invite is inherently mutual.
"""

import argparse
import csv
import json
import logging
import sys
import time
import uuid
from pathlib import Path

from kafka import KafkaProducer
from kafka.errors import KafkaError
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from ingestion.schemas.collaboration_event import CollaborationEvent

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

TOPIC = "collaboration.events.raw"
CHANNEL = "calendar"


def build_producer(bootstrap_servers: str) -> KafkaProducer:
    """Create a KafkaProducer with JSON serialization.

    Args:
        bootstrap_servers: Comma-separated Kafka broker addresses.

    Returns:
        Configured KafkaProducer instance.
    """
    return KafkaProducer(
        bootstrap_servers=bootstrap_servers.split(","),
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),
        acks="all",
        retries=3,
    )


def _make_reverse_event(event: CollaborationEvent) -> CollaborationEvent:
    """Create the inverse direction of a calendar event (B → A from A → B)."""
    return CollaborationEvent(
        event_id=str(uuid.uuid4()),
        source_employee_id=event.target_employee_id,
        target_employee_id=event.source_employee_id,
        channel=event.channel,
        direction="invited",
        department_source=event.department_target,
        department_target=event.department_source,
        timestamp=event.timestamp,
        weight=event.weight,
    )


def produce_from_csv(
    edges_csv: Path,
    producer: KafkaProducer,
    delay_ms: int = 100,
) -> int:
    """Publish bidirectional Calendar events from edges.csv to Kafka.

    Each row with channel='calendar' produces 2 events: A→B and B→A.

    Args:
        edges_csv: Path to the edges CSV file generated by generate_org_data.py.
        producer: Configured KafkaProducer.
        delay_ms: Milliseconds to wait between event pairs.

    Returns:
        Total number of events published (2× the number of matched rows).
    """
    count = 0
    with edges_csv.open("r", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["channel"] != CHANNEL:
                continue

            try:
                fwd = CollaborationEvent(
                    event_id=row["event_id"],
                    source_employee_id=row["source_employee_id"],
                    target_employee_id=row["target_employee_id"],
                    channel=row["channel"],
                    direction="invited",
                    department_source=row["department_source"],
                    department_target=row["department_target"],
                    timestamp=row["timestamp"],
                    weight=float(row["weight"]),
                )
            except ValidationError as exc:
                logger.warning("Skipping invalid row event_id=%s: %s", row.get("event_id"), exc)
                continue

            rev = _make_reverse_event(fwd)

            for event in (fwd, rev):
                try:
                    producer.send(TOPIC, value=event.model_dump(mode="json"))
                    count += 1
                except KafkaError as exc:
                    logger.error("Kafka send failed for event_id=%s: %s", event.event_id, exc)

            if count % 500 == 0 and count > 0:
                logger.info("Published %d %s events", count, CHANNEL)
            time.sleep(delay_ms / 1000.0)

    producer.flush()
    return count


def main() -> None:
    parser = argparse.ArgumentParser(
        description=f"Kafka producer — channel: {CHANNEL} (bidirectional)"
    )
    parser.add_argument("--edges-csv", type=Path, default=Path("data/synthetic/edges.csv"))
    parser.add_argument("--bootstrap-servers", default="localhost:9092")
    parser.add_argument("--delay-ms", type=int, default=100)
    parser.add_argument("--dry-run", action="store_true",
                        help="Count events without publishing")
    args = parser.parse_args()

    if args.dry_run:
        with args.edges_csv.open("r", newline="", encoding="utf-8") as f:
            n = sum(1 for row in csv.DictReader(f) if row["channel"] == CHANNEL)
        logger.info("[dry-run] Would publish %d %s events (%d pairs × 2)", n * 2, CHANNEL, n)
        return

    producer = build_producer(args.bootstrap_servers)
    try:
        n = produce_from_csv(args.edges_csv, producer, args.delay_ms)
        logger.info("Finished: published %d %s events to %s", n, CHANNEL, TOPIC)
    finally:
        producer.close()


if __name__ == "__main__":
    main()
