#!/usr/bin/env python3
"""Kafka producer for Slack collaboration events.

Reads edges.csv, filters channel == 'slack', and publishes each event
to the collaboration.events.raw topic with a configurable delay.
"""

import argparse
import csv
import json
import logging
import sys
import time
from pathlib import Path

from kafka import KafkaProducer
from kafka.errors import KafkaError
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from ingestion.schemas.collaboration_event import CollaborationEvent

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

TOPIC = "collaboration.events.raw"
CHANNEL = "slack"


def build_producer(bootstrap_servers: str) -> KafkaProducer:
    """Create a KafkaProducer with JSON serialization.

    Args:
        bootstrap_servers: Comma-separated Kafka broker addresses.

    Returns:
        Configured KafkaProducer instance.
    """
    return KafkaProducer(
        bootstrap_servers=bootstrap_servers.split(","),
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),
        acks="all",
        retries=3,
    )


def produce_from_csv(
    edges_csv: Path,
    producer: KafkaProducer,
    delay_ms: int = 100,
) -> int:
    """Publish Slack events from edges.csv to Kafka.

    Args:
        edges_csv: Path to the edges CSV file generated by generate_org_data.py.
        producer: Configured KafkaProducer.
        delay_ms: Milliseconds to wait between events (simulates real-time streaming).

    Returns:
        Number of events successfully published.
    """
    count = 0
    with edges_csv.open("r", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["channel"] != CHANNEL:
                continue

            try:
                event = CollaborationEvent(
                    event_id=row["event_id"],
                    source_employee_id=row["source_employee_id"],
                    target_employee_id=row["target_employee_id"],
                    channel=row["channel"],
                    direction=row["direction"],
                    department_source=row["department_source"],
                    department_target=row["department_target"],
                    timestamp=row["timestamp"],
                    weight=float(row["weight"]),
                )
            except ValidationError as exc:
                logger.warning("Skipping invalid row event_id=%s: %s", row.get("event_id"), exc)
                continue

            try:
                producer.send(TOPIC, value=event.model_dump(mode="json"))
                count += 1
                if count % 500 == 0:
                    logger.info("Published %d %s events", count, CHANNEL)
                time.sleep(delay_ms / 1000.0)
            except KafkaError as exc:
                logger.error("Kafka send failed for event_id=%s: %s", event.event_id, exc)

    producer.flush()
    return count


def main() -> None:
    parser = argparse.ArgumentParser(description=f"Kafka producer — channel: {CHANNEL}")
    parser.add_argument("--edges-csv", type=Path, default=Path("data/synthetic/edges.csv"))
    parser.add_argument("--bootstrap-servers", default="localhost:9092")
    parser.add_argument("--delay-ms", type=int, default=100)
    parser.add_argument("--dry-run", action="store_true",
                        help="Count events without publishing")
    args = parser.parse_args()

    if args.dry_run:
        with args.edges_csv.open("r", newline="", encoding="utf-8") as f:
            n = sum(1 for row in csv.DictReader(f) if row["channel"] == CHANNEL)
        logger.info("[dry-run] Would publish %d %s events", n, CHANNEL)
        return

    producer = build_producer(args.bootstrap_servers)
    try:
        n = produce_from_csv(args.edges_csv, producer, args.delay_ms)
        logger.info("Finished: published %d %s events to %s", n, CHANNEL, TOPIC)
    finally:
        producer.close()


if __name__ == "__main__":
    main()
